name: ischooler_student
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:

  logger: ^2.0.2+1
  awesome_bottom_bar: ^1.2.4
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.10
  dio: ^5.4.0
  dot_navigation_bar: ^1.0.2
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_floating_bottom_bar: ^1.2.0
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_smart_dialog: ^4.9.6
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.3
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1
  mockito: ^5.4.4
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  supabase_flutter: ^2.3.2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
#   image_path: "assets/icons/ischooler_splash_logo.png"
#   adaptive_icon_foreground: "assets/icons/ischooler_icon_logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:

    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 600
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
