export 'package:ischooler/features/dashboard/data/models/all_models.dart';
// export 'package:ischooler/features/class_data/data/models/class_model.dart';
// export 'package:ischooler/features/grades/data/models/grade_model.dart';
// export 'package:ischooler/features/users/admins/data/models/admin_model.dart';
// export 'package:ischooler/features/users/instructor/data/models/instructor_model.dart';
// export 'package:ischooler/features/users/students/data/models/student_model.dart';
// export 'package:ischooler/features/users/user_model.dart';
// export 'package:ischooler/features/users/admin_roles/data/models/admin_role_model.dart';
// export 'package:ischooler/features/instructor_assignments/data/models/instructor_assignment_model.dart';
// export 'package:ischooler/features/subjects/data/models/subject_model.dart';
